//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fileNoteFIDRel
    {
        public Nullable<long> FID { get; set; }
        public Nullable<long> fileNoteID { get; set; }
        public long fileNoteFIDRelId { get; set; }
    
        public virtual fileInfo fileInfo { get; set; }
        public virtual fileNote fileNote { get; set; }
    }
}
