//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fileNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fileNote()
        {
            this.fileNoteFIDRels = new HashSet<fileNoteFIDRel>();
        }
    
        public long fileNoteID { get; set; }
        public Nullable<long> FID { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> noteTime { get; set; }
    
        public virtual fileInfo fileInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fileNoteFIDRel> fileNoteFIDRels { get; set; }
    }
}
