//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fileInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fileInfo()
        {
            this.fileNotes = new HashSet<fileNote>();
            this.fileNoteFIDRels = new HashSet<fileNoteFIDRel>();
            this.nfsActions = new HashSet<nfsAction>();
            this.PCIs = new HashSet<PCI>();
            this.PIIs = new HashSet<PII>();
            this.RETs = new HashSet<RET>();
            this.SPECs = new HashSet<SPEC>();
            this.unknowns = new HashSet<unknown>();
        }
    
        public long FID { get; set; }
        public Nullable<long> volID { get; set; }
        public Nullable<int> pciFlag { get; set; }
        public Nullable<int> piiFlag { get; set; }
        public Nullable<int> specFlag { get; set; }
        public Nullable<int> retFlag { get; set; }
        public Nullable<int> unknownFlag { get; set; }
        public Nullable<int> publicFlag { get; set; }
        public Nullable<int> internalFlag { get; set; }
        public Nullable<int> confidentialFlag { get; set; }
        public Nullable<int> confidentialsFlag { get; set; }
        public Nullable<int> secretFlag { get; set; }
    
        public virtual volume volume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fileNote> fileNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fileNoteFIDRel> fileNoteFIDRels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nfsAction> nfsActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCI> PCIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PII> PIIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RET> RETs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPEC> SPECs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unknown> unknowns { get; set; }
    }
}
