//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nfsAction
    {
        public long actionID { get; set; }
        public Nullable<int> actionTypeID { get; set; }
        public Nullable<long> FID { get; set; }
        public Nullable<long> empID { get; set; }
        public Nullable<System.DateTime> actionTime { get; set; }
    
        public virtual actionType actionType { get; set; }
        public virtual employee employee { get; set; }
        public virtual fileInfo fileInfo { get; set; }
    }
}
