//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCI
    {
        public Nullable<long> FID { get; set; }
        public long pciID { get; set; }
        public Nullable<int> filtertypeID { get; set; }
        public string pciFileName { get; set; }
        public string pciPath { get; set; }
        public string pciContainerPath { get; set; }
        public string pciVolumeName { get; set; }
        public string pciObjectType { get; set; }
        public string pciOwner { get; set; }
        public string pciSize { get; set; }
        public string pciCtime { get; set; }
        public string pciMTime { get; set; }
        public string pciATime { get; set; }
        public string pciMD5 { get; set; }
    
        public virtual fileInfo fileInfo { get; set; }
        public virtual filterTypeRef filterTypeRef { get; set; }
    }
}
