//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPEC
    {
        public Nullable<long> FID { get; set; }
        public long specID { get; set; }
        public Nullable<int> filtertypeID { get; set; }
        public string specFileName { get; set; }
        public string specPath { get; set; }
        public string specContainerPath { get; set; }
        public string specVolumeName { get; set; }
        public string specObjectType { get; set; }
        public string specOwner { get; set; }
        public string specSize { get; set; }
        public string specCtime { get; set; }
        public string specMTime { get; set; }
        public string specATime { get; set; }
        public string specMD5 { get; set; }
    
        public virtual fileInfo fileInfo { get; set; }
        public virtual filterTypeRef filterTypeRef { get; set; }
    }
}
