//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unknown
    {
        public Nullable<long> FID { get; set; }
        public long unkID { get; set; }
        public Nullable<int> filtertypeID { get; set; }
        public string unkFileName { get; set; }
        public string unkPath { get; set; }
        public string unkContainerPath { get; set; }
        public string unkVolumeName { get; set; }
        public string unkObjectType { get; set; }
        public string unkOwner { get; set; }
        public string unkSize { get; set; }
        public string unkCtime { get; set; }
        public string unkMTime { get; set; }
        public string unkATime { get; set; }
        public string unkMD5 { get; set; }
    
        public virtual fileInfo fileInfo { get; set; }
        public virtual filterTypeRef filterTypeRef { get; set; }
    }
}
