//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class V1Entities : DbContext
    {
        public V1Entities()
            : base("name=V1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actionType> actionTypes { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<empRel> empRels { get; set; }
        public virtual DbSet<fileInfo> fileInfoes { get; set; }
        public virtual DbSet<fileNote> fileNotes { get; set; }
        public virtual DbSet<fileNoteFIDRel> fileNoteFIDRels { get; set; }
        public virtual DbSet<filterTypeRef> filterTypeRefs { get; set; }
        public virtual DbSet<nfsAction> nfsActions { get; set; }
        public virtual DbSet<PCI> PCIs { get; set; }
        public virtual DbSet<PII> PIIs { get; set; }
        public virtual DbSet<RET> RETs { get; set; }
        public virtual DbSet<SPEC> SPECs { get; set; }
        public virtual DbSet<unknown> unknowns { get; set; }
        public virtual DbSet<volume> volumes { get; set; }
    }
}
